name: Tests
on:
 push:
 pull_request:
jobs:
 testen:
 runs-on: ubuntu-latest
 steps:
 - name: Code ophalen
 uses: actions/checkout@v4
 - name: Python installeren
 uses: actions/setup-python@v5
 with:
 python-version: "3.12"
 - name: Pakketten installeren
 run: pip install -r requirements.txt
 - name: Tests draa
   run: pytest -v
